version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:3000"
    environment:
      - NODE_ENV=production
      - TENANT_ID=${TENANT_ID}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI:-https://localhost/auth/redirect}
      - PORT=3000
      - SESSION_SECRET=${SESSION_SECRET}
      - AUTHORITY=https://login.microsoftonline.com/
      - GRAPH_API_ENDPOINT=https://graph.microsoft.com/
      - API_SCOPES=https://graph.microsoft.com/.default
    volumes:
      - ./data:/app/data
    restart: unless-stopped
